name: Deploy preprod

on:
  workflow_dispatch:
    inputs:
      envToRun:
        type: choice
        description: 'Env to run [ test | ci | preprod | prod ]'
        required: true
        default: preprod
        options:
          - test
          - ci
          - preprod
          - prod

jobs:

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: ${{ inputs.envToRun }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: react - Build, tag, and push image to Amazon ECR
        id: react-build-image
        env:
          REACT_ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REACT_ECR_REPOSITORY: training-calendar-frontend-preprod-nginx
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
          --build-arg REACT_API_BASE_URL="${{ env.REACT_API_BASE_URL }}" \
          -t $REACT_ECR_REGISTRY/$REACT_ECR_REPOSITORY:$IMAGE_TAG \
          -f react.Dockerfile .
          docker tag  $REACT_ECR_REGISTRY/$REACT_ECR_REPOSITORY:$IMAGE_TAG $REACT_ECR_REGISTRY/$REACT_ECR_REPOSITORY:latest
          docker push $REACT_ECR_REGISTRY/$REACT_ECR_REPOSITORY --all-tags
          echo "image=$REACT_ECR_REGISTRY/$REACT_ECR_REPOSITORY:$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      - name: Download task definition preprod-training-calendar-frontend
        run: |
          aws ecs describe-task-definition --task-definition preprod-training-calendar-front --query taskDefinition > task-definition.json

      - name: Fill in the new react image ID in the Amazon ECS task definition
        id: react-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: react
          image: ${{ steps.react-build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition frontend-pack
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.react-task-def.outputs.task-definition }}
          service: preprod-training-calendar-frontend
          cluster: preprod-training-calendar
          wait-for-service-stability: true